src/books/urls.py
from django.urls import path

from . import views

urlpatterns = [

    # path('', views.BookListView.as_view(), name="book_list"),
    # path('^(?P<pk>\d+)/$', views.BookDetailView.as_view(), name="book_detail"),
    path('', views.book_list_view, name="book_list"),
    path('details/<int:index>/',views.book_detail_view, name='book_detail'),
    path('refined-search/', views.refined_view, name="refined_view"),
    path('sorted/', views.sorted_book, name="sorted"),
    path('books/', views.book_list_view)
    

]

src/bookstore/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home_page'),
    path('about/', views.about, name='home_about'),
    path('wishlist/', views.wishlist_default, name='wish_list_default'),
    path('wishlist/<int:wishlistID>', views.wishlist, name='wish_list'),
    path('create-wishlist/<int:userID>/<int:wishlistID>/<str:name>', views.create_wistlist, name='create_wishlist'),
    path('delete-wishlist/<int:userID>/<int:wishlistID>', views.delete_wistlist, name='create_wishlist'),
    path('edit-wishlist/<int:wishlistID>/<str:name>', views.edit_wistlist, name='edit_wishlist'),
    path('add-to-wishlist/<int:wishlistID>/<int:bookID>', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove-from-wishlist/<int:wishlistID>/<int:bookID>', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('move-to-wishlist/<int:bookId>/<int:wishlistID1>/<int:wishlistID2>', views.move_wistlist, name='move_to_wishlist')
]

src/geektext/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path, include
from accounts import views as user_views
from accounts.views import guest_register_view
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('books/', include('books.urls')),
    path('', include('bookstore.urls')),
    path('addresses/', include('addresses.urls')),
    url('cart/', include("carts.urls", namespace='cart')),
    url('save/', include("saveitems.urls", namespace='save')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/saveitems/urls.py
from django.conf.urls import url

from .views import (
        cart_home, 
        cart_update, 
        )

app_name ='cart_home'
app_name ='cart_update'

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^update/$', cart_update, name='update'),
]

src/bookstore/models.py
from django.db import models
from django.db.models import Avg
from django.utils.timezone import now


# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Author(models.Model):
    full_name = models.CharField(max_length=30)
    email = models.EmailField(null=True)
    description = models.TextField(max_length=600, null=True, blank=True)
    dob = models.CharField(max_length=12, null=True, blank=True)
    birthplace = models.CharField(max_length=75, null=True, blank=True)
    education = models.CharField(max_length=100, null=True, blank=True)
    website = models.URLField(null=True)
    image = models.FileField(null=True, blank=True)

    def __str__(self):
        return u'%s' % self.full_name

    def get_absolute_url(self):
        return "/book/author/%s/" % self.id

    class Meta:
        ordering = ['full_name']

class Book(models.Model):
    authors = models.ManyToManyField(Author, blank=True)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=120)
    description = models.TextField(max_length=600, null=True, blank=True)
    image = models.FileField(null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=5, default=0)
    publication_date = models.CharField(max_length=12, null=True, blank=True)
    genre = models.CharField(max_length=50, blank=True, null=True)
    pages = models.IntegerField(default=0)
    avg_rating = models.DecimalField(decimal_places=1, max_digits=2, default=0)
    sales_rank = models.IntegerField(default=0)
    top_sellers = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    # def __str__(self):
    #     return self.title

    def get_absolute_url(self):
        return "/book/%s/" % self.id

    # def author(self):
    #     return Author.objects.filter(book__authors__book=self.id).distinct()

    def rating_avg(self):
        book = Book.objects.get(id=self.id)
        # return list(book.rating_set.aggregate(Avg('rating')).values())[0]
        pass

    def rating_count(self):
        # return Rating.objects.all().filter(book=self).count()
        pass

    class Meta:
        ordering = ['title']

src/bookstore/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from books.models import Book,Author
from accounts.models import WishList, WishListNames
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse


def home(request):
    books = Book.objects.all()
    page = request.GET.get('page', 1)

    paginator = Paginator(books, 12)
    try:
        book_by_page = paginator.page(page)
    except PageNotAnInteger:
        book_by_page = paginator.page(1)
    except EmptyPage:
        book_by_page = paginator.page(paginator.num_pages)

    context = {'book_by_page': book_by_page}
    return render(request, 'bookstore/home.html', context)
# Create your views here.

def about(request):
    return render(request, 'bookstore/about.html')

def create_wistlist(request, userID, wishlistID, name):
    user = User.objects.get(id=userID)
    WishListNames(user=user, wishlist_num=wishlistID, name=name).save()
    return JsonResponse({'msg':'Success'})

def edit_wistlist(request, wishlistID, name):
    wishlistItem = WishListNames.objects.filter(user=request.user, wishlist_num=wishlistID)
    wishlistItem.update(name=name)
    return JsonResponse({'msg':'Success'})

def delete_wistlist(request, userID, wishlistID):
    user = User.objects.get(id=userID)
    WishList.objects.filter(wishlist_num=wishlistID).delete()
    WishListNames.objects.get(user=user, wishlist_num=wishlistID).delete()
    return JsonResponse({'msg':'Success'})

def add_to_wishlist(request, wishlistID, bookID):
    if WishList.objects.filter(user=request.user, book=Book.objects.get(id=bookID), wishlist_num=wishlistID).exists():
        return JsonResponse({'msg':'Already exists'})
    wishlistItem = WishList(user=request.user, book=Book.objects.get(id=bookID), wishlist_num=wishlistID)
    wishlistItem.save()
    return JsonResponse({'msg':'Success'})

def move_wistlist(request, bookId, wishlistID1, wishlistID2):
    wishlistitem = WishList.objects.filter(user=request.user, book=Book.objects.get(id=bookId), wishlist_num=wishlistID1)
    wishlistitem2 = WishList.objects.filter(user=request.user, book=Book.objects.get(id=bookId), wishlist_num=wishlistID2)
    if not wishlistitem2:
        WishList(user=request.user, book=Book.objects.get(id=bookId), wishlist_num=wishlistID2).save()
    if wishlistitem:
        wishlistitem.delete()
    return JsonResponse({'msg':'Success'})

def remove_from_wishlist(request, wishlistID, bookID):
    wishlistItem = WishList.objects.filter(user=request.user, book=Book.objects.get(id=bookID), wishlist_num=wishlistID)
    if wishlistItem:
        wishlistItem.delete()
    return JsonResponse({'msg':'Success'})

def wishlist_default(request):
    return redirect('/wishlist/0')

def wishlist(request, wishlistID):
    wishlist_names = WishListNames.objects.all()
    wishlist = WishList.objects.filter(user=request.user)
    wishlist_names_d = [None, None, None]
    for w in wishlist_names:
        wishlist_names_d[w.wishlist_num] = w

    context = {
        "wishlist": wishlist,
        "wishlistNames": wishlist_names_d,
        "numWishlist": range(3),
        "wishlistNum": wishlistID
    }

    return render(request, 'bookstore/wishlist.html', context)

src/bookstore/templates/bookstore/about.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>About</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>
<body>
    <h1>About Page</h1>
</body>
</html>

src/bookstore/templates/bookstore/base.html
{% load static %}
<!doctype html>
    <html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        {% if title %}
            <title>GeekText Bookstore- {{ title }}</title>
        {% else %}
            <title>GeekText Bookstore</title>
        {% endif %}

        <link rel="stylesheet" type="text/css" href="{% static 'bookstore/css/main.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'books/books.css' %}">
        <script>
            function addToWishlist(bookId, wishlistID, elementId) {
                fetch('http://localhost:8000/add-to-wishlist/'+wishlistID+'/'+bookId)
                .then((data) => { return data.json()})
                .then((body) => console.log(body))
            }

            function removeFromWishList(bookId, wishlistID) {
                fetch('http://localhost:8000/remove-from-wishlist/'+wishlistID+'/'+bookId)
                .then((data) => { return data.json()})
                .then((body) => console.log(body))
                location.reload();
            }

            function moveToWishlist(bookId, wishlistID1, wishlistID2) {
                fetch('http://localhost:8000/move-to-wishlist/'+bookId+'/'+wishlistID1+'/'+wishlistID2)
                .then((data) => { return data.json()})
                .then((body) => console.log(body))
                location.reload();
            }

            function wishlistControl(wishlistId, inputId, userId, action) {
                if(action == 'Create') {
                    var name = document.getElementById(inputId).value;
                    fetch('http://localhost:8000/create-wishlist/'+userId+'/'+wishlistId+'/'+name)
                    .then((data) => { return data.json()})
                    .then((body) => console.log(body))

                    document.getElementById('wishlist-name-'+wishlistId).innerHTML = 
                    `<b>`+name+`</b>
                    <button onclick="wishlistControl(`+wishlistId+`, 'create-wistlist-`+wishlistId+`', `+userId+`, 'Delete')">Delete</button>`
                } else if(action == 'Edit') {
                    var name = document.getElementById(inputId).value;
                    fetch('http://localhost:8000/edit-wishlist/'+wishlistId+'/'+name)
                    .then((data) => { return data.json()})
                    .then((body) => console.log(body))
                    document.getElementById('wishlist-title-'+wishlistId).innerHTML = name;
                } else if(action == 'Delete') {
                    fetch('http://127.0.0.1:8000/delete-wishlist/'+userId+'/'+wishlistId)
                    .then((data) => { return data.json()})
                    .then((body) => console.log(body))

                    document.getElementById('wishlist-name-'+wishlistId).innerHTML = 
                    `<input id="create-wistlist-`+wishlistId+`" type="text" placeholder="Create Wishlist"/>
                    <button onclick="wishlistControl(`+wishlistId+`, 'create-wistlist-`+wishlistId+`', `+userId+`, 'Create')">+</button>`
                }
            }
        </script>
        {% include 'bookstore/css.html'%}

        {% block base_head %}{% endblock %}
    </head>
    <body>
        {% include 'bookstore/navbar.html' %}
{% if messages %}
            <div class="alert alert-info alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {% for message in messages %}
                {{ message }}
                {% endfor %}
            </div>
    {% endif %}
            {% block home_content %} {% endblock %}
            

            {% block register_content %} 



          
            {% endblock register_content %}
            
            




            {% block listContent %} {% endblock %}
        {% include 'bookstore/js.html'%}
    </body>
</html>

src/bookstore/templates/bookstore/css.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

src/bookstore/templates/bookstore/home.html
{% extends "bookstore/base.html" %}
{% load static %}

<title> Home Page</title>


{% block base_head %}
<link rel='stylesheet' href='{% static "css/main.css" %}'>
{% endblock %}

{% block home_content %}

<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'bookstore/img/book1.jpeg' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-caption d-none d-md-block">
            <h1>Welcome to Geektext</h1>
            <p>Find all the books for your geek</p>
          </div>
          <div class="carousel-item">
            <img src="{% static 'bookstore/img/book2.jpg' %}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'bookstore/img/book3.jpg' %}" class="d-block w-100" alt="...">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div><br><br>

<div class="container bg-light">
<!-- <div class="col-lg-9"> -->
<div class="row">
{% for i in book_by_page %}
            <div class="col-lg-4 col-md-6 mb-4 mt-4 {{i.category}}">
              <div class="card" style="width: 18rem;">
                  <a href="/books/details/{{i.id}}"><img class="card-img-top" src={{i.image.url}} alt=""></a>
                <div class="card-body">
                  <h5 class="card-title">
                    <a href="/books/details/{{i.id}}">{{i.title}}</a>
                  </h5>

                  <small class="text-muted">
                      by {{i.author}}<cite title="Source Title">{{Books}}</cite>
                  <cite title="Source Title">{{Books}}</cite>
                 

                  </small>

                

                  <h5>${{i.price}}</h5>
                  <p class="card-text"></p>
                </div>
                <div class="card-footer">

                 <a href="/books/details/{{i.id}}" > Details </a>
                 {% include 'update-cart.html' with product=i cart=cart %}
                 {% include 'save-items.html' with product=i save=cart %}
                </div>
              </div>
            </div>
{% endfor %}
</div>


        {% if book_by_page.has_other_pages %}
  <ul class="pagination">
    {% if book_by_page.has_previous %}
      <li><a href="?page={{ book_by_page.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in book_by_page.paginator.page_range %}
      {% if book_by_page.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if book_by_page.has_next %}
      <li><a href="?page={{ book_by_page.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>


{% endif %}

</div>

</div>

{% endblock %} 

src/bookstore/templates/bookstore/js.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

src/bookstore/templates/bookstore/navbar.html
{% url 'login' as login_url %}
{% url 'register' as register_url %}
{% load static %}
<!-- <div class="container"> -->
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
        <div class="container">
        <!-- <a class="navbar-brand" href="{{ home_url }}"><img src="{% static 'img/logo1.svg' %}" width="160" height="30" class="d-inline-block align-top" alt="">{% if brand_name %} {{ brand_name }} {% else %} GeekText {% endif %}</a> -->
        <a class="navbar-brand" href="{% url 'home_page' %}"><img src="{% static 'bookstore/img/logo1.svg' %}" width="160" height="30" class="d-inline-block align-top" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        {% include 'search/snippets/search-form.html' %}
        <!-- <li class="nav-item dropdown">
                <a class="nav-item dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    All Categories
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Arts & Music</a>
                    <a class="dropdown-item" href="#">Biographies</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
        </li> -->
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav justify-content-end">


                <li class="nav-item">
                    <a class="nav-link" href='{% url "cart:home" %}'><i class="fas fa-shopping-cart"></i> Cart {{ request.session.cart_items }}</a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href='{% url "save:home" %}'><i class="fas fa-heart" style ="color: blue"></i>  {{ request.session.cart_save }}</a>
                    </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-alt"></i>
                        Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

                        {% if user.is_authenticated %}

                            <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'profile' %}"><i class="fas fa-user"></i> Profile</a>
                                <a class="dropdown-item" href="{% url 'wish_list_default' %}"><i class="fas fa-heart"></i> Wish List</a>
                                <a class="dropdown-item" href="#"><i class="fas fa-shopping-cart"></i> Cart</a>
                                <div class="dropdown-divider"></div>
                                <a class="btn btn-primary btn-sm btn-info btn-block" href="{% url 'logout' %}" role="button">Sign out</a>

                            <li class="nav-item"></li>
                                <a class="navbar-brand" href="{% url 'profile' %}">
                                        <img src="{{user.profile.image.url }}" width="30" height="30" class="d-inline-block align-top rounded-circle" alt="">
                                        {{ accounts.username }}
                                </a>
                            </li>
                        {% else %}
                            <a class="btn btn-primary btn-sm btn-warning btn-block" href="{% url 'login' %}" role="button">Sign In</a>
                            <a class="btn btn-primary btn-sm btn-success btn-block" href="{% url 'register' %}" role="button">Register</a>

                        {% endif %}

                        <!-- <a class="dropdown-item" href="#">Loguot</a> -->
                    </div>
                </li>
            </ul>
        </div>
      </nav>
    </div>

src/bookstore/templates/bookstore/wishlist.html
{% extends "bookstore/base.html" %}
{% load static %}

<title>Wishlist</title>


{% block base_head %}
<!-- <link rel='stylesheet' href='{% static "css/main.css" %}'> -->
{% endblock %}

{% block home_content %}
<div>
    {% for i in wishlistNames %}
        <div id="wishlist-name-{{forloop.counter0}}">
            {% if i is not None %}
                {% if forloop.counter0 is not wishlistNum %}
                    <a href="/wishlist/{{forloop.counter0}}">View</a>
                {% endif %}
                <b id="wishlist-title-{{forloop.counter0}}" {% if forloop.counter0 is wishlistNum %} style="background-color: lightgreen" {% endif %} >{{i.name}}</b>
                <button onclick="wishlistControl({{i.wishlist_num}}, 'create-wistlist-{{i.wishlist_num}}', {{user.id}}, 'Delete')">Delete</button>
                <input type="text" id="edit-wistlist-{{forloop.counter0}}" placeholder="Edit name"/>
                <button onclick="wishlistControl({{forloop.counter0}}, 'edit-wistlist-{{forloop.counter0}}', {{user.id}}, 'Edit')">Edit</button>
            {% else %}
                <input id="create-wistlist-{{forloop.counter0}}" type="text" placeholder="Create Wishlist"/>
                <button onclick="wishlistControl({{forloop.counter0}}, 'create-wistlist-{{forloop.counter0}}', {{user.id}}, 'Create')">+</button>
            {% endif %}
        </div>
    {% endfor %}
    {% for item in wishlist %}
        {% if item.wishlist_num is wishlistNum %}
            <div class="col-lg-4 col-md-6 mb-4 {{item.book.category}}">
                <div class="card h-100">
                <a href="#"><img class="card-img-top" src={{item.book.image.url}} alt=""></a>
                <div class="card-body">
                    <h4 class="card-title">
                    <a href="/books/details/{{item.book.id}}">{{item.book.title}}</a>
                    </h4>

                    <h5>${{item.book.price}}</h5>
                    <p class="card-text"></p>
                </div>
                <div class="card-footer">
                    <a href="/books/details/{{item.book.id}}"> Details</a>
                    <a href="#" class="btn btn-primary"><i class="fas fa-shopping-cart"></i> Add to Cart</a>
                    <button onclick="removeFromWishList({{item.book.id}}, {{wishlistNum}})" class="btn btn-danger float-right"><i class="fas fa-times"></i></button>
                    {% for i in wishlistNames %}
                        {% if i is not None and forloop.counter0 is not wishlistNum %}
                            <button onclick="moveToWishlist({{item.book.id}}, {{wishlistNum}}, {{i.wishlist_num}})" class="btn btn-success">Move To {{i.name}} Wishlist <i class="fas fa-heart"></i></button>
                        {% endif %}
                    {% endfor %}
                </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>

{% endblock %} 